version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - TZ=Asia/Seoul

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 6379:6379

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    container_name: user-es
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - "discovery.type=single-node"