name: Build and Push Docker images to ECR

on:
  push:
    branches:
      - main
      - development

jobs:
  build-rest-api-gateway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      - name: Build and push Docker image for rest-api-gateway
        id: build-image-rest-api-gateway
        run: |
          IMAGE_TAG=${{ secrets.ECR_REPOSITORY }}dev-rest-api-gateway:${{ github.sha }}
          docker build -t $IMAGE_TAG ./rest-api-gateway
          docker push $IMAGE_TAG

      - name: Logout from ECR
        run: docker logout ${{ secrets.ECR_REPOSITORY }}


  build-grpc-user:
    runs-on: ubuntu-latest
    needs: build-rest-api-gateway  # 이 단계는 rest-api-gateway 빌드가 끝난 후에 실행됨

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ${{ secrets.AWS_REGION }}

      - name: Build and push Docker image for grpc-user
        id: build-image-grpc-user
        run: |
          IMAGE_TAG=${{ secrets.ECR_REPOSITORY }}-grpc-user:${{ github.sha }}
          docker build -t $IMAGE_TAG ./grpc-user
          docker push $IMAGE_TAG

      - name: Logout from ECR
        run: docker logout ${{ secrets.ECR_REPOSITORY }}


