name: Build and Push Docker images to ECR

on:
  push:
    branches:
      - main
      - development

jobs:
  build-rest-api-gateway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      - name: Build and push Docker image for rest-api-gateway
        run: |
          IMAGE_TAG=${{ secrets.ECR_REPOSITORY }}-rest-api-gateway:${{ github.sha }}
          docker build -t $IMAGE_TAG ./apps/rest-api-gateway
          docker push $IMAGE_TAG

      - name: Logout from ECR
        run: docker logout ${{ secrets.ECR_REPOSITORY }}

  build-grpc-user:
    runs-on: ubuntu-latest
    needs: build-rest-api-gateway  # 이 단계는 rest-api-gateway 빌드가 끝난 후에 실행됨

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      - name: Build and push Docker image for grpc-user
        run: |
          IMAGE_TAG=${{ secrets.ECR_REPOSITORY }}-grpc-user:${{ github.sha }}
          docker build -t $IMAGE_TAG ./apps/grpc-user
          docker push $IMAGE_TAG

      - name: Logout from ECR
        run: docker logout ${{ secrets.ECR_REPOSITORY }}
