name: Build and Push Docker images to ECR

on:
  push:
    branches:
      - main
      - development

jobs:
  build-rest-api-gateway:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      - name: Build and push Docker image for rest-api-gateway
        run: |
          IMAGE_TAG=${{ secrets.ECR_REPOSITORY }}rest-api-gateway-dev
          docker build -t $IMAGE_TAG -f apps/rest-api-gateway/Dockerfile .
          docker push $IMAGE_TAG

      - name: Logout from ECR
        run: docker logout ${{ secrets.ECR_REPOSITORY }}

      - name: Update ECS service with new image
        run: |
          # Update the service with the new task definition
          aws ecs update-service --cluster ${{ secrets.ECS_CLUSTER_NAME }} --service ${{ secrets.ECS_SERVICE_NAME }} --task-definition $task_definition_name --force-new-deployment --region ap-northeast-2"